using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace JonasWischeropp.Unity.EditorTools.ShaderGraph {
    public class ModifierStack : ScriptableObject {
        public string shaderName;
        public Shader sourceShader;
        public Shader outputShader;
        
        [SerializeReference]
        private List<Modifier> _modifiers = new List<Modifier>();
        
        public void UpdateTarget() {
            string sourcePath = Util.GetPath(sourceShader);
            string targetPath = Util.GetPath(outputShader);

            string code = GenerateShaderCode(sourcePath);
            code = ConvertCode(code);
            File.WriteAllText(targetPath, code);
            AssetImporter importer = AssetImporter.GetAtPath(targetPath);
            importer.SaveAndReimport();
        }
        
        string ConvertCode(string code) {
            code = "/*\n"
                +  " Don't edit this file. Any changes will be overwritten!!!\n"
                +  " This file is automatically generated from the shader graph file:\n"
                + $" {Util.GetPath(sourceShader)}\n"
                +  " Using https://github.com/JonasWischeropp/unity-shader-graph-modifier\n"
                +  "*/\n\n"

                + $"Shader \"{shaderName}\""
                + code[code.IndexOf('\n')..];
            foreach (Modifier modifier in _modifiers) {
                code = modifier.Apply(code);
            }
            return code;
        }

        public IEnumerable<Type> GetAddableOptions() {
            return TypeCache.GetTypesDerivedFrom<Modifier>().Where(IsAddAllowed);
        }

        public void AddModifier(Type type) {
            if (!IsAddAllowed(type)) {
                throw new ArgumentException($"'{type}' can only be added once");
            }
            Modifier modifier = (Modifier)Activator.CreateInstance(type);
            _modifiers.Add(modifier);
            modifier.SetDisplayName();
        }
        
        bool IsAddAllowed(Type type) {
            BindingFlags flags = BindingFlags.FlattenHierarchy | BindingFlags.Static | BindingFlags.Public;
            bool unique = (bool)type.GetMethod("IsUnique", flags).Invoke(null, null);
            if (!unique) {
                return true;
            }
            return ! _modifiers.Any(modifier => modifier.GetType() == type);
        }
        
        public void RemoveAll() {
            _modifiers.Clear();
        }

        public void OnDestroy() {
            // This function is not called reliably (don't rely on it being called in editor)
            var sourceImporter = AssetImporter.GetAtPath(Util.GetPath(sourceShader));
            var targetImporter = AssetImporter.GetAtPath(Util.GetPath(outputShader));
            ClearModifierStackID(sourceImporter);
            ClearModifierStackID(targetImporter);
        }
        
        public static bool TryLoadStack(string path, out ModifierStack stack) {
            return TryLoadStack(AssetImporter.GetAtPath(path), out stack);
        }

        public static bool TryLoadStack(AssetImporter importer, out ModifierStack stack) {
            if (TryLoadModifierStackID(importer, out GUID id)) {
                stack = AssetDatabase.LoadAssetAtPath<ModifierStack>(
                    AssetDatabase.GUIDToAssetPath(id));
                return stack != null;
            }
            stack = null;
            return false;
        }

        public static bool TryLoadModifierStackID(AssetImporter importer, out GUID id) {
            id = new GUID(importer.userData);
            return !id.Empty();
        }
        
        public static void StoreModifierStackID(AssetImporter importer, GUID id) {
            importer.userData = id.ToString();
        }

        public static void ClearModifierStackID(AssetImporter importer) {
            importer.userData = "";
        }

        // This function is copied from a post by Farl_Lee (last accessed 2026/01/25)
        // https://discussions.unity.com/t/how-to-get-shader-source-code-from-script/839046/6
        private static object GetGraphData(string shaderAssetPath) {
            var importer = AssetImporter.GetAtPath(shaderAssetPath);

            var textGraph = File.ReadAllText(importer.assetPath, Encoding.UTF8);
            var graphObjectType = Type.GetType("UnityEditor.Graphing.GraphObject, Unity.ShaderGraph.Editor")!;

            // var graphObject = CreateInstance<GraphObject>();
            var graphObject = ScriptableObject.CreateInstance(graphObjectType);

            graphObject.hideFlags = HideFlags.HideAndDontSave;
            bool isSubGraph;
            var extension = Path.GetExtension(importer.assetPath).Replace(".", "");
            switch (extension)
            {
                case "shadergraph":
                    isSubGraph = false;
                    break;
                case "ShaderGraph":
                    isSubGraph = false;
                    break;
                case "shadersubgraph":
                    isSubGraph = true;
                    break;
                default:
                    throw new Exception($"Invalid file extension {extension}");
            }
            var assetGuid = AssetDatabase.AssetPathToGUID(importer.assetPath);
           
            // graphObject.graph = new GraphData { assetGuid = assetGuid, isSubGraph = isSubGraph, messageManager = null };
            var graphObject_graphProperty = graphObjectType.GetProperty("graph")!;
            var graphDataType = Type.GetType("UnityEditor.ShaderGraph.GraphData, Unity.ShaderGraph.Editor")!;
            var graphDataInstance = Activator.CreateInstance(graphDataType);
            graphDataType.GetProperty("assetGuid")!.SetValue(graphDataInstance, assetGuid);
            graphDataType.GetProperty("isSubGraph")!.SetValue(graphDataInstance, isSubGraph);
            graphDataType.GetProperty("messageManager")!.SetValue(graphDataInstance, null);
            graphObject_graphProperty.SetValue(graphObject, graphDataInstance);

            // MultiJson.Deserialize(graphObject.graph, textGraph);
            // = MultiJson.Deserialize<JsonObject>(graphObject.graph, textGraph, null, false);
            var multiJsonType = Type.GetType("UnityEditor.ShaderGraph.Serialization.MultiJson, Unity.ShaderGraph.Editor")!;
            var deserializeMethod = multiJsonType.GetMethod("Deserialize")!;
            var descrializeGenericMethod = deserializeMethod.MakeGenericMethod(graphDataType);
            descrializeGenericMethod.Invoke(null, new object[] { graphDataInstance, textGraph, null, false });

            // graphObject.graph.OnEnable();
            graphDataType.GetMethod("OnEnable")!.Invoke(graphDataInstance, null);

            // graphObject.graph.ValidateGraph();
            graphDataType.GetMethod("ValidateGraph")!.Invoke(graphDataInstance, null);

            // return graphData.graph
            return graphDataInstance;
        }

        // This function is a modified version of a post by Farl_Lee (last accessed 2026/01/25)
        // https://discussions.unity.com/t/how-to-get-shader-source-code-from-script/839046/6
        public static string GenerateShaderCode(string shaderAssetPath, string shaderName = null) {
            Type generatorType =
                Type.GetType("UnityEditor.ShaderGraph.Generator, Unity.ShaderGraph.Editor")!;
            Type modeType =
                Type.GetType("UnityEditor.ShaderGraph.GenerationMode, Unity.ShaderGraph.Editor")!;

            shaderName ??= Path.GetFileNameWithoutExtension(shaderAssetPath);

            object graphData = GetGraphData(shaderAssetPath);

            object forReals = ((FieldInfo)modeType.GetMember("ForReals")[0]).GetValue(null);

            object generator = Activator.CreateInstance(
                generatorType,
#if UNITY_6000_3_OR_NEWER // note: I am not sure in what version the interface changed (somewhere between 2022.3.62f2 and 6000.3)
                // Void .ctor(UnityEditor.ShaderGraph.GraphData graphData, UnityEditor.ShaderGraph.AbstractMaterialNode outputNode, UnityEditor.ShaderGraph.GenerationMode mode, System.String primaryShaderName, UnityEditor.ShaderGraph.Target[] targets, UnityEditor.ShaderGraph.AssetCollection assetCollection, Boolean humanReadable, Boolean hidden)
                new object[] { graphData, null, forReals, shaderName, null, null, true, false} // not sure what hidden refers to
#else
                // new Generator(graphData, outputNode:null, GenerationMode.ForReals, assetName, target:null, assetCollection:null, humanReadable:true);
                new object[] { graphData, null, forReals, shaderName, null, null, true }
#endif
            );
            object shaderCode = generatorType
                .GetProperty("generatedShader", BindingFlags.Public | BindingFlags.Instance)!
                .GetValue(generator);

            return (string)shaderCode;
        }
    }
}
