using System.IO;
using UnityEditor;
using UnityEngine;

namespace JonasWischeropp.Unity.EditorTools.ShaderGraph {
    [CustomEditor(typeof(Shader))]
    public class ModifierEditor : Editor {
        bool _isShaderGraph; 
        AssetImporter _importer;

        GUID _modifierStackID;
        ModifierStack _modifierStack;
        SerializedObject _modifierStackSO;

        bool foldOutIsExpanded = true;

        void OnEnable() {
            string shaderPath = Util.GetPath(target);
            _importer = AssetImporter.GetAtPath(shaderPath);
            _isShaderGraph = shaderPath.EndsWith("shadergraph");

            if (ModifierStack.TryLoadModifierStackID(_importer, out _modifierStackID)) {
                _modifierStack = AssetDatabase.LoadAssetAtPath<ModifierStack>(
                    AssetDatabase.GUIDToAssetPath(_modifierStackID));
                if (_modifierStack != null) {
                    _modifierStackSO = new SerializedObject(_modifierStack);
                }
            }
        }

        void OnDisable() {
            _modifierStack?.UpdateTarget();
            _modifierStackSO?.Dispose();
        }

        public override void OnInspectorGUI() {
            EditorGUI.EndDisabledGroup();
            if (_modifierStackSO == null) {
                if (_isShaderGraph) {
                    if (GUILayout.Button("Create Modifier Stack")) {
                        CreateModifierStack();
                    }
                }
            }
            else {
                if (_isShaderGraph) {
                    OnShaderGraphInspectorGUI(_modifierStackSO, _modifierStack);
                }
                else {
                    OnShaderInspectorGUI();
                }
            }
            EditorGUI.BeginDisabledGroup(true);
            
            base.OnInspectorGUI();
        }
        
        void OnShaderGraphInspectorGUI(SerializedObject modifierStackSO, ModifierStack modifierStack) {
            foldOutIsExpanded = EditorGUILayout.BeginFoldoutHeaderGroup(foldOutIsExpanded,
                "Shader Graph Modifier", null, OnMenuAction);
            if (!foldOutIsExpanded) {
                return;
            }
            EditorGUI.indentLevel += 1;
            using (new EditorGUI.DisabledGroupScope(true)) {
                EditorGUILayout.ObjectField("Modifier Stack", modifierStack,
                    typeof(ModifierStack), false);
            }
            ModifierStackEditor.OnDrawModifiers(_modifierStackSO, _modifierStack);
            EditorGUI.indentLevel -= 1;
        }

        void OnMenuAction(Rect position) {
            var menu = new GenericMenu();        
            menu.AddItem(new GUIContent("Remove"), false, RemoveModifierStack);
            menu.DropDown(position);
        }
        
        void RemoveModifierStack() {
            _modifierStack = null;
            _modifierStackSO.Dispose();
            _modifierStackSO = null;

            AssetDatabase.DeleteAsset(AssetDatabase.GUIDToAssetPath(_modifierStackID));
            _modifierStackID = new GUID();
        }

        void OnShaderInspectorGUI() {
            GUIStyle warningTextStyle = new GUIStyle();
            warningTextStyle.normal.textColor = Color.red;
            warningTextStyle.wordWrap = true;

            string shaderInspectorName = ObjectNames.NicifyVariableName(nameof(_modifierStack.sourceShader));
            GUILayout.Label("Don't edit this file. Any changes will be overwritten!!!\n"
                + $"This file is automatically generated from a shader graph file ({shaderInspectorName}).",
                warningTextStyle);

            EditorGUI.indentLevel += 1;
            using (new EditorGUI.DisabledGroupScope(true)) {
                EditorGUILayout.PropertyField(_modifierStackSO.FindProperty("sourceShader"));
                EditorGUILayout.ObjectField("Modifier Stack", _modifierStack,
                    typeof(ModifierStack), false);
            }
            EditorGUI.indentLevel -= 1;
        }

        void CreateModifierStack() {
            _modifierStack = ScriptableObject.CreateInstance<ModifierStack>();

            string directory = Path.GetDirectoryName(_importer.assetPath) + "/";
            string sourceFileName = Path.GetFileNameWithoutExtension(_importer.assetPath);

            string modifierStackName = sourceFileName + "_ModifierStack";
            string modifierStackFileName = directory + modifierStackName + ".asset";
            AssetDatabase.CreateAsset(_modifierStack, modifierStackFileName);
            AssetDatabase.SaveAssets();

            _modifierStackSO = new SerializedObject(_modifierStack);
            _modifierStackSO.FindProperty("m_Name").stringValue = modifierStackName;
            _modifierStackSO.FindProperty("shaderName").stringValue = ((Shader)target).name;
            _modifierStackSO.FindProperty("sourceShader").objectReferenceValue = target;
            
            string code = ModifierStack.GenerateShaderCode(_importer.assetPath);
            string targetFileName = directory + sourceFileName + "_Modified.shader";
            File.WriteAllText(targetFileName, code);
            AssetDatabase.Refresh();

            Shader targetShader = AssetDatabase.LoadAssetAtPath<Shader>(targetFileName);
            _modifierStackSO.FindProperty("outputShader").objectReferenceValue = targetShader;

            _modifierStackSO.ApplyModifiedPropertiesWithoutUndo();

            ModifierStack.StoreModifierStackID(_importer,
                AssetDatabase.GUIDFromAssetPath(modifierStackFileName));
            ModifierStack.StoreModifierStackID(AssetImporter.GetAtPath(targetFileName),
                AssetDatabase.GUIDFromAssetPath(modifierStackFileName));
            _importer.SaveAndReimport();
        }
    }
}
